### ISSUE TITLE
if clean install then package cross-env needs to be installed: add to doc for others

### ISSUE THREAD

**Issue by hugoledoux** [STEMLab/InViewer#6]
before running npm start:
```bash
npm install --save-dev cross-env
```

**Comment by hgryoo** [comment]
Hello,

cross-env is already registered under devDependencies in package.json.
So, when you install, cross-env will be installed.
Could you explain in detail about the problem?

Hyung-Gyu Ryoo

**Comment by hugoledoux** [comment]
hmmm, I had never used node.js and npm. I just installed on macOS and when I tried to run `npm start` I got loads of errors, one related to cross-env. So I googled and installed that, and it all worked.

full error log
```
hugo$ npm start

> InViewer@0.9.0 start /Users/hugo/software/InViewer
> cross-env NODE_ENV=development nodemon build/scripts/start --exec babel-node

sh: cross-env: command not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! InViewer@0.9.0 start: `cross-env NODE_ENV=development nodemon build/scripts/start --exec babel-node`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the InViewer@0.9.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?
```

**Comment by JungHam** [comment]
Hello, 
before run `npm start`, did you run `npm install` ? 
I guessed it by the log -
```
npm WARN Local package.json exists, but node_modules missing, did you mean to install?
```
If you run `npm install` then the folder named `node_modules` is automatically created. 
The folder is needed to run server because the folder is used for containing lib used in InViewer.

**Comment by hugoledoux** [comment]
oh I see now, no I didn't.

So it's fine, sorry.
